import { MODES_BY_ID, STORAGE_KEYS } from '../constants.js';

export const RUNTIME_CONSTANTS = {
  BASE_UI_SCALE: 0.74,
  UI_DISTANCE_MIN: 1.3,
  UI_DISTANCE_MAX: 3.3,
  UI_DISTANCE_DEFAULT: (1.3 + 3.3) / 2,
  XR_FRAMEBUFFER_SCALE: 1.25,
  XR_FOVEATION: 0,
  DISABLE_COMPOSITION_LAYERS_IN_VR: false,
  SURFACE_TRIGGER_GRAB_DELAY_MS: 180,
  SCREEN_BASE_WIDTH: 18,
  SCREEN_BASE_HEIGHT: 10.125,
  SCREEN_MESH_COMPENSATION: 1.15,
  SPATIAL_GRAB_GAIN_MIN: 8,
  SPATIAL_GRAB_GAIN_MAX: 18,
  SPATIAL_GRAB_GAIN_SLOPE: 0.9,
  SPATIAL_GRAB_SMOOTHING_MIN: 0.28,
  SPATIAL_GRAB_SMOOTHING_MAX: 0.42,
  SPATIAL_GRAB_SMOOTHING_SLOPE: 0.03,
  LAYER_SYNC_INTERVAL_MS: 33,
  LAYER_POSITION_THRESHOLD_METERS: 0.003,
  LAYER_ROTATION_THRESHOLD_DEG: 0.35
};

export function createRuntimeContext(overlay, styleEl, jellyfinVideo, modeId) {
  const RC = RUNTIME_CONSTANTS;
  return {
    overlay,
    styleEl,
    jellyfinVideo,

    active: true,

    renderer: null,
    scene: null,
    camera: null,
    vrButton: null,
    arButton: null,

    uiGroup: null,
    floatingPanels: [],
    mainUiState: null,
    interactables: [],
    textObjects: [],
    layoutCardMeshes: [],
    layoutBackgroundMesh: null,
    settingsBackgroundMesh: null,
    settingsGroup: null,
    layoutGroup: null,
    infoGroup: null,
    infoContentGroup: null,
    infoLeftColumnGroup: null,
    infoRightColumnGroup: null,
    infoButtonMesh: null,
    infoBackgroundMesh: null,
    settingsUiDistTrack: null,
    settingsDimmerTrack: null,
    infoLeftStatusLines: [],
    infoRightStatusLines: [],
    updateInfoPanelStatus: () => {},
    infoPerfToggleMesh: null,
    infoDebugToggleMesh: null,

    debugPanelGroup: null,
    debugPanelState: null,
    debugPanelBackgroundMesh: null,
    debugPanelHandleMesh: null,
    debugPanelCloseMesh: null,
    debugPanelMetricsToggleMesh: null,
    debugPanelFaceToggleMesh: null,
    debugPanelTextLines: [],
    updateDebugPanelStatus: () => {},

    bgMesh: null,
    timeCurrentObj: null,
    timeDurationObj: null,
    titleTextObj: null,
    playIconGroup: null,
    pauseIconGroup: null,
    stereoToggleLabel: null,
    seekBg: null,
    seekBuf: null,
    seekFill: null,
    seekPreviewGroup: null,
    seekPreviewImage: null,
    seekPreviewTimeObj: null,
    seekHoverVisible: false,
    seekHoverRatio: 0,
    volSliderGroup: null,
    ptSliderGroup: null,
    ptSliderUpdateFill: null,
    volSliderVisible: false,
    ptSliderVisible: false,
    marqueeOffset: 0,
    marqueeDir: 0,
    marqueePauseTimer: 0,

    toolbarVersionBtn: null,
    immersiveDebugScreen: null,
    surfaceRoot: null,
    videoGrabControllers: [],
    panelGrabControllers: [],

    videoTexture: null,
    materials: {},
    meshes: {},

    mediaBinding: null,
    mediaVideoLayer: null,
    mediaLayerStatus: 'unavailable',
    mediaLayerReason: 'not-initialized',
    mediaLayerMode: 'mesh',
    mediaLayerKey: '',
    textRendererStatus: 'troika-msdf',
    mediaLayerRevision: 0,
    mediaLayerDebugSpec: null,

    projectionLayerStatus: 'unknown',
    projectionLayerReason: 'not-initialized',
    xrSessionMode: 'unknown',
    xrEnvironmentBlendMode: 'unknown',
    xrModeDetection: 'unknown',
    xrPolyfillState: 'not-checked',
    xrLayersPolyfillState: 'not-checked',
    xrBindingState: 'unknown',
    xrRenderStateLayers: 'unknown',
    xrRenderStateBaseLayer: 'unknown',
    xrMediaBindingFactory: 'unknown',
    xrMediaLayerSupport: 'unknown',
    xrSelectedLayerType: 'none',
    xrLayerLastError: 'none',
    xrLayerCommitCount: 0,
    xrLayerSyncCount: 0,
    xrLayerRecreateCount: 0,
    xrLastCommittedLayers: null,
    xrCachedSupportSession: null,
    xrCachedSupport: null,

    trickplayItemId: '',
    trickplayInfo: null,
    trickplayFetchState: 'idle',
    trickplayActiveTileIndex: -1,
    trickplayActiveFrameIndex: -1,
    trickplayActiveTexture: null,
    trickplayTileCache: new Map(),
    trickplayTileLoads: new Map(),
    trickplayTileLoader: null,

    state: {
      mode: MODES_BY_ID[modeId] || MODES_BY_ID['360-mono'],
      isImmersive: false,
      swapEyes: false,
      uiVisible: true,
      uiAnchorType: 'center',
      uiAnchorOrigin: null,
      uiAnchorForward: null,
      lastInteraction: Date.now(),
      uiDistance: Math.min(RC.UI_DISTANCE_MAX, Math.max(RC.UI_DISTANCE_MIN, Math.abs(parseFloat(localStorage.getItem(STORAGE_KEYS.uiDistance))) || RC.UI_DISTANCE_DEFAULT)),
      uiScale: parseFloat(localStorage.getItem(STORAGE_KEYS.uiScale)) || 1.0,
      isAR: false,
      passthroughEnabled: false,
      passthroughBrightness: 1.0,
      screenCurvature: 0.0,
      effectiveScreenCurve: 0.0,
      screenSize: 1.0,
      screenDistance: -12.0,
      stereoLock: 'auto',
      screenFacePlayer: localStorage.getItem(STORAGE_KEYS.screenFacePlayer) !== '0',
      uiFacePlayer: localStorage.getItem(STORAGE_KEYS.uiFacePlayer) !== '0',
      debugPanelFacePlayer: true,
      debugMetricsEnabled: false,
      showingDebugPanel: false,
      lastModeChangeSource: 'initial',
      lastUiOpenSource: 'initial',
      lastUiCloseSource: 'initial',
      showingSettings: false,
      showingLayout: false,
      forceFallback: false
    },

    debugMetrics: {
      fps: 0,
      avgFrameMs: 0,
      minFrameMs: 0,
      maxFrameMs: 0,
      slowFrames: 0,
      rendererCalls: 0,
      rendererTriangles: 0,
      rendererLines: 0,
      rendererPoints: 0,
      rendererTextures: 0,
      rendererPrograms: 0,
      jsHeapMb: null,
      layerCommitCount: 0,
      layerRecreateCount: 0,
      layerSyncCount: 0
    },
    debugMetricsFrameCount: 0,
    debugMetricsAccumMs: 0,
    debugMetricsMinMs: Infinity,
    debugMetricsMaxMs: 0,
    debugMetricsSlowFrameCount: 0,
    debugMetricsLastSampleAt: 0,
    debugPanelLastRefreshAt: 0,
    infoPanelLastRefreshAt: 0,
    lastFrameAt: 0,

    _surfaceTempPosition: null,
    _surfaceTempQuaternion: null,
    _surfaceTempScale: null,
    _surfaceLastLayerPosition: null,
    _surfaceLastLayerQuaternion: null,
    _lastLayerTransformSyncAt: 0,
    _surfaceLastLayerKey: '',
    _dragPlane: null,
    _dragIntersectPoint: null,
    _dragPlaneNormal: null,
    _debugPanelTempLookTarget: null,
    _debugPanelDragOffset: null,
    _viewerPosition: null,
    _viewerForward: null,
    _panelGrabDelta: null,
    _passthroughDimmerFallbackState: false,
    _passthroughDimmerSessionFallbackLocked: false
  };
}
